site_name: dm-bip
site_url: https://linkml.io/dm-bip/
repo_url: https://github.com/linkml/dm-bip
repo_name: linkml/dm-bip

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Pipeline User Guide: pipeline_user_docs.md
  - LinkML Tools:
    - Schema Automator: schema_automator.md

markdown_extensions:
  - tables
  - fenced_code
  - toc:
      permalink: true
