"""
Unit normalization lookup table.

Direct translation of units.do from RTIInternational/NHLBI-BDC-DMC-HV.
Maps free-form unit strings (lowered, spaces removed) to canonical UCUM representations.
"""

# Mapping of source unit variants → canonical UCUM unit.
# Keys are lowercase with spaces removed (matching the Stata preprocessing).
UNIT_NORMALIZATION: dict[str, str] = {
    # %
    "percent": "%",
    # %{WBCs}
    "%{wbcs}": "%{WBCs}",
    "percentoftotalleukocytes": "%{WBCs}",
    # %{normal}
    "%ofnormal": "%{normal}",
    # 1/2cup (serving sizes)
    "1fruit,1/2cupor5dried": "1/2cup",
    "1/2cupor2-4sticks": "1/2cup",
    "1fruitor1/2cup": "1/2cup",
    "1/2cupofcarrotsor2-3oz.ofjuice": "1/2cup",
    "1/2fruitor1/2cup": "1/2cup",
    "1/2cupvegetables,or1cupofsoup": "1/2cup",
    "1earor1/2cup": "1/2cup",
    # 10*3/mm3
    "10^3/mm3": "10*3/mm3",
    "103/mm3": "10*3/mm3",
    "x1000/mm3": "10*3/mm3",
    "th/cmm": "10*3/mm3",
    # 10*3/uL
    "x10e3/ul": "10*3/uL",
    "thou/ul(thousandspermicroliter)": "10*3/uL",
    "10^3cells/ul": "10*3/uL",
    "10*3/ul": "10*3/uL",
    "thousandspermicroliter": "10*3/uL",
    "x10^3/ul": "10*3/uL",
    "thousands/ul": "10*3/uL",
    "10^3/ul": "10*3/uL",
    # 10*6/mm3
    "106/mm3": "10*6/mm3",
    "m/cmm": "10*6/mm3",
    "10^6/mm3": "10*6/mm3",
    # 10*6/uL
    "count,x10e12": "10*6/uL",
    "10*6/ul": "10*6/uL",
    "10^6/ul": "10*6/uL",
    "x10e6/ul": "10*6/uL",
    "millions/ul": "10*6/uL",
    # 10*9/L
    "count,x10e9": "10*9/L",
    "10*9/l": "10*9/L",
    "10^9/l": "10*9/L",
    # 3-4oz
    "3-4oz.": "3-4oz",
    # Celsius
    "c": "Cel",
    "cel": "Cel",
    # Liters
    "l": "L",
    "litres": "L",
    "liters": "L",
    # IU
    "[iu]": "[IU]",
    "i.u.": "[IU]",
    "iu": "[IU]",
    # IU/L
    "[iu]/l": "[IU]/L",
    "iu/l": "[IU]/L",
    "u/l": "[IU]/L",
    # IU/dL
    "[iu]/dl": "[IU]/dL",
    "iu/dl": "[IU]/dL",
    # IU/mL
    "[iu]/ml": "[IU]/mL",
    "iu/ml": "[IU]/mL",
    # cups
    "cup": "[cup_us]",
    # feet
    "ft": "[ft_us]",
    "feet": "[ft_us]",
    # Hounsfield units
    "hu": "[hnsf'U]",
    "[hnsf'u]": "[hnsf'U]",
    "hounsfieldunits(hu)": "[hnsf'U]",
    # inches
    "inches": "[in_us]",
    "inches,tonextlower1/4inch": "[in_us]",
    "inchestonextlower1/4inch": "[in_us]",
    "in": "[in_us]",
    "tonextlower1/4inch": "[in_us]",
    # pounds
    "lb": "[lb_av]",
    "lbs": "[lb_av]",
    "pounds": "[lb_av]",
    "pounds,tonearestpound": "[lb_av]",
    # ounces
    "1oz.or1/2cup": "[oz_av]",
    "oz": "[oz_av]",
    "1oz": "[oz_av]",
    # pH
    "[ph]": "[pH]",
    "ph": "[pH]",
    # tablespoons
    "tbs": "[tbs_us]",
    "1tbs": "[tbs_us]",
    # years
    "yearsold": "a",
    "years": "a",
    "year": "a",
    "numberofyearssinceexam1": "a",
    # agatston unit
    "agatstonunit": "agatstonunit",
    # centimeters
    "centimeters": "cm",
    # centiseconds
    "hundredthsofsecond": "cs",
    "hundredthsofasecond": "cs",
    "hundredthsofasec.": "cs",
    "hundredsofsecond": "cs",
    # days
    "days": "d",
    "dayssinceexam1": "d",
    "numberofdayssinceexam1": "d",
    # deciliters
    "dl": "dL",
    "deciliter": "dL",
    # dg/dL
    "dg/dl": "dg/dL",
    "decigrams/100ml": "dg/dL",
    # decimeters
    "cmx10": "dm",
    # femtoliters
    "fl": "fL",
    "femtoliter": "fL",
    # grams
    "gm": "g",
    # g/day
    "g/day": "g/d",
    "g/24hr": "g/d",
    # g/dL
    "gm/dl": "g/dL",
    "g/dl": "g/dL",
    # hours
    "hrs": "h",
    "hr": "h",
    "hour": "h",
    "hours": "h",
    # mL
    "ml": "mL",
    # mL/day
    "ml/day": "mL/d",
    "ml/d": "mL/d",
    "ml/alcohol/day": "mL/d",
    # mL/min/1.73m2
    "ml/min/{1.73_m2}": "mL/min/{1.73_m2}",
    "ml/minper1.73m2": "mL/min/{1.73_m2}",
    "ml/min/1.73m2": "mL/min/{1.73_m2}",
    "ml/min/1.73m^2": "mL/min/{1.73_m2}",
    # mL/s
    "ml/s": "mL/s",
    "ml/sec": "mL/s",
    # mIU/L
    "mul": "m[IU]/L",
    "miu/l": "m[IU]/L",
    "mu/l": "m[IU]/L",
    "m[iu]/l": "m[IU]/L",
    # mIU/mL
    "miu/ml": "m[IU]/mL",
    "mu/ml": "m[IU]/mL",
    "amiu/ml": "m[IU]/mL",
    "m[iu]/ml": "m[IU]/mL",
    # meq/L
    "meq/liter": "meq/L",
    "meq/l": "meq/L",
    # meq/L(x100)
    "meq/l(x100)": "meq/L(x100)",
    "meq/liter(x100)": "meq/L(x100)",
    # mg/L
    "mg/l": "mg/L",
    # mg/L{FEU}
    "mg/lfeu": "mg/L{FEU}",
    # mg/day
    "mg/24hr": "mg/d",
    "mg/day": "mg/d",
    "mg/24hours": "mg/d",
    # mg/dL
    "mgperdl": "mg/dL",
    "mg/dl": "mg/dL",
    "mgper100ml": "mg/dL",
    "mg/100ml": "mg/dL",
    # mg/g
    "mg/gcr": "mg/g",
    # mg/mL
    "mg/ml": "mg/mL",
    # minutes
    "minutes": "min",
    # mm/h
    "mm/hr": "mm/h",
    # mm3(10*3/uL)
    "mm3(10^3/ul)": "mm3(10*3/uL)",
    "mm3(1,000,000/microliter)": "mm3(10*3/uL)",
    "mm3(1,000,000permicroliter)": "mm3(10*3/uL)",
    # mmHg
    "tonearest2mm/hg": "mm[Hg]",
    "mm/hg": "mm[Hg]",
    "hgmm": "mm[Hg]",
    "mm[hg]": "mm[Hg]",
    "tonearest2mmhg": "mm[Hg]",
    "mmhg": "mm[Hg]",
    # mmol/L
    "mmolperl": "mmol/L",
    "mmol/l": "mmol/L",
    # mmol/dL
    "mmoles/dl": "mmol/dL",
    "mmol/dl": "mmol/dL",
    # months
    "months": "mo",
    "month": "mo",
    # milliseconds
    "msec": "ms",
    "milliseconds": "ms",
    "millisec": "ms",
    # ng/L
    "ng/l": "ng/L",
    # ng/mL
    "ng/ml": "ng/mL",
    "plasmang/ml": "ng/mL",
    # nmol/min/mL
    "nmol/min/ml": "nmol/min/mL",
    # none → empty string (data quality workaround)
    "numberofsiblings": "none",
    "n/a": "none",
    "codes": "none",
    "numberofkids": "none",
    # pg/mL
    "pg/ml": "pg/mL",
    # pg/cell
    "pg/cell": "pg/{cell}",
    # pmol/L
    "pmol/l": "pmol/L",
    # seconds
    "seconds": "s",
    # microvolts
    "uv": "uV",
    "microvolts": "uV",
    # uIU/mL
    "uiu/ml": "u[IU]/mL",
    "uu/ml": "u[IU]/mL",
    "microu/ml": "u[IU]/mL",
    "u[iu]/ml": "u[IU]/mL",
    # ug/L
    "ug/l": "ug/L",
    "mcg/l": "ug/L",
    # ug/dL
    "ug/dl": "ug/dL",
    # ug/mL
    "ug/ml": "ug/mL",
    # um3
    "microm3": "um3",
    "um3(micrometerscubed)": "um3",
    # {#}/d
    "num/day": "{#}/d",
    # {#}/mL
    "num/ml": "{#}/mL",
    "platelets/ml": "{#}/mL",
    "{#}/ml": "{#}/mL",
    # {#}/uL
    "{#}/ul": "{#}/uL",
    "num/ul": "{#}/uL",
    "number/microl": "{#}/uL",
    # beats/min
    "beatsperminute": "{beats}/min",
    "beats/minute": "{beats}/min",
    "beats": "{beats}/min",
    "beats/min": "{beats}/min",
    "beatspermin": "{beats}/min",
    "bpm": "{beats}/min",
    # breaths/min
    "breaths/min": "{breath}/min",
    # cells/uL
    "kcell/mcl": "{cells}/uL",
    "{cells}/ul": "{cells}/uL",
    "kcell/ul": "{cells}/uL",
    "cells/ul": "{cells}/uL",
    # cigarettes/day
    "cigarettesperday": "{cigarettes}/d",
    "cigarette/day": "{cigarettes}/d",
    "cigarettes/day": "{cigarettes}/d",
    # events/hour
    "events/hr": "{events}/h",
    "#/hr": "{events}/h",
    "events/hour": "{events}/h",
    # ratio
    "ratio": "{ratio}",
    # score
    "scale": "{score}",
    "score": "{score}",
    # servings
    "1serving": "{servings}",
    "drinks": "{servings}",
    "servings": "{servings}",
    # servings/day
    "servings/day": "{servings}/d",
    # servings/week
    "servings/week": "{servings}/wk",
    "drinks/week": "{servings}/wk",
    "servingsperweek": "{servings}/wk",
}


def normalize_unit(value: str | None) -> str:
    """
    Normalize a unit string to its canonical UCUM representation.

    Mirrors the Stata units.do logic: lowercase, strip spaces, look up in table.
    Values mapping to "none" are returned as empty string.
    """
    if not value or not isinstance(value, str):
        return ""
    key = value.lower().replace(" ", "")
    result = UNIT_NORMALIZATION.get(key, key)
    if result == "none":
        return ""
    return result
