id: https://example.org/repro
name: repro
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Survey:
    attributes:
      id:
        range: integer
        identifier: true
      zipcode:
        range: string
      satisfaction:
        range: satisfaction_enum

enums:
  satisfaction_enum:
    permissible_values:
      '1':
        description: Very Unsatisfied
      '2':
        description: Unsatisfied
      '3':
        description: Neutral
      '4':
        description: Satisfied
      '5':
        description: Very Satisfied
      'foo':
        description: Foo foo foo
