name: Auto-deployment of Documentation
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --group docs

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        uv run sphinx-apidoc -o . ../src/dm_bip/ --ext-autodoc -f
        uv run sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        force: true
        folder: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
